### ISSUE TITLE
Arrow Keys not working in Kubuntu 18.04

### ISSUE THREAD

**Issue by hookumsnivy** [Zren/kwin-tabbox-thumbnail_grid#4]
I'm using Kubuntu 18.04 and I can't get the arrow keys to work. Any ideas?

**Comment by Zren** [comment]
https://repology.org/project/kwin/versions

Ubuntu 18.04 only has KWin 5.12.

https://github.com/Zren/kwin-tabbox-thumbnail_grid/blob/master/Changelog.md#v5---april-18-2019

> * Fix focus so arrow keys work in Plasma 5.15+

Arrow keys aren't [forwarded to the QML skin before 5.15](https://phabricator.kde.org/D16693), so it won't work for you until Plasma is updated to that version.
