### ISSUE TITLE
Could you make it bigger?

### ISSUE THREAD

**Issue by ghost** [Zren/kwin-tabbox-thumbnail_grid#6]
Now it looks a little small.

**Comment by Zren** [comment]
Are you using a HiDPI screen? It looks like my github version wasn't scaled by DPI.

* https://github.com/Zren/kwin-tabbox-thumbnail_grid/blob/master/package/contents/ui/main.qml#L121

However the tabbox theme was upstreamed into KDE and does scale by DPI:

* https://invent.kde.org/plasma/kdeplasma-addons/-/blob/master/windowswitchers/thumbnail_grid/contents/ui/main.qml#L120

**Comment by ghost** [comment]
Yes, I'm using a HiDPI screen, yestoday I saw the theme had been upstreamed into KDE (and it can work well), so I closed this issue.
